baseurl: "https://www.rdegges.com/"
languageCode: "en-us"
title: "Randall Degges"
theme: "rdegges"
params:
  author: "Randall Degges"
  copyrightstart: "2009"
  copyrightstop: "2015"
  description: "The personal website of Randall Degges: programmer, speaker, author and entrepreneur."
  subtitle: "Random thoughts of a happy programmer."
